# Predicting whether an email is spam or not

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/14_naive_bayes/spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.describe()

Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le=LabelEncoder()

In [6]:
df['Spam']=le.fit_transform(df['Category'])
df

Category                                            Message  Spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [18]:
X=df['Message']
y=df['Spam']

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

In [25]:
cv=CountVectorizer()

In [44]:
X_count_vector=cv.fit_transform(X)
X_count_vector=X_count_vector.toarray()
X_count_vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
from sklearn.model_selection import train_test_split

In [51]:
X_train,X_test,y_train,y_test=train_test_split(X_count_vector,y,train_size=0.8,random_state=6)

In [52]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
y_train

1527    0
338     0
5032    0
2674    0
3250    0
       ..
335     1
4714    0
2004    0
227     1
2761    0
Name: Spam, Length: 4457, dtype: int32

# Using Gaussian NB

In [54]:
from sklearn.naive_bayes import GaussianNB
GNB=GaussianNB()

In [55]:
GNB.fit(X_train,y_train)

GaussianNB()

In [61]:
y_predicted=GNB.predict(X_test)
y_predicted[1:]

array([0, 0, 1, ..., 1, 0, 0])

In [60]:
y_test

2958    0
2482    0
2745    0
3556    1
4509    0
       ..
548     0
564     1
4701    1
4432    0
5513    0
Name: Spam, Length: 1115, dtype: int32

In [67]:
GNB.score(X_test,y_test)

0.8753363228699551

# Using Multinomial NB

In [64]:
from sklearn.naive_bayes import MultinomialNB
MNB=MultinomialNB()

In [65]:
MNB.fit(X_train,y_train)

MultinomialNB()

In [66]:
y_predicted=MNB.predict(X_test)
y_predicted[1:]

array([0, 0, 1, ..., 1, 0, 0])

In [69]:
y_test

2958    0
2482    0
2745    0
3556    1
4509    0
       ..
548     0
564     1
4701    1
4432    0
5513    0
Name: Spam, Length: 1115, dtype: int32

In [68]:
MNB.score(X_test,y_test)

0.97847533632287

The only problem here is that whenever we need to check the propability of an email that whether it is spam or not,we firt need to convert it into a CountVactorizer be cause out models dont work on stings.See the example below:

In [71]:
#Example:

#email='hi, its me, zain ,reply to my email immidiately.'
#MNB.predict(email)

# Solution: Using sklearn pipeline

In [87]:
from sklearn.pipeline import Pipeline

In [88]:
p_classifier =Pipeline([
    ('CountVactorizer',CountVectorizer()),
    ('MNB',MultinomialNB())
])

In [89]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [90]:
y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Spam, Length: 5572, dtype: int32

In [91]:
from sklearn.model_selection import train_test_split

In [113]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.8,random_state=6)

In [114]:
X_train

1527    Wow ... I love you sooo much, you know ? I can...
338                            Just sleeping..and surfing
5032     Hey... Very inconvenient for your sis a not huh?
2674    Good afternoon, my boytoy ... How are you feel...
3250                     Sorry, I can't help you on this.
                              ...                        
335     Valentines Day Special! Win over £1000 in our ...
4714    Big brother‘s really scraped the barrel with t...
2004    S....s...india going to draw the series after ...
227     Will u meet ur dream partner soon? Is ur caree...
2761           I dont thnk its a wrong calling between us
Name: Message, Length: 4457, dtype: object

In [115]:
y_train

1527    0
338     0
5032    0
2674    0
3250    0
       ..
335     1
4714    0
2004    0
227     1
2761    0
Name: Spam, Length: 4457, dtype: int32

In [116]:
X_test

2958    I would but I'm still cozy. And exhausted from...
2482                    K.:)do it at evening da:)urgent:)
2745                            Tick, tick, tick ... Babe
3556    From next month get upto 50% More Calls 4 Ur s...
4509                             Not able to do anything.
                              ...                        
548                      Sorry that took so long, omw now
564     GENT! We are trying to contact you. Last weeke...
4701    WIN: We have a winner! Mr. T. Foley won an iPo...
4432       2mro i am not coming to gym machan. Goodnight.
5513    Yes. Please leave at  &lt;#&gt; . So that at  ...
Name: Message, Length: 1115, dtype: object

In [117]:
p_classifier.fit(X_train,y_train)

Pipeline(steps=[('CountVactorizer', CountVectorizer()),
                ('MNB', MultinomialNB())])

In [118]:
p_classifier.predict(X_test)

array([0, 0, 0, ..., 1, 0, 0])

In [119]:
y_test

2958    0
2482    0
2745    0
3556    1
4509    0
       ..
548     0
564     1
4701    1
4432    0
5513    0
Name: Spam, Length: 1115, dtype: int32

In [120]:
p_classifier.score(X_test,y_test)

0.9919282511210762

In [124]:
#Example :
email=['hi, its me, zain ,reply to my email immidiately.',
       "Not able to do anything.",
       "Did you hear about the new Divorce Barbie? It comes with all of Ken's stuff!",
       "URGENT! Your Mobile No. was awarded £2000 Bonus Caller Prize on 5/9/03 This is our final try to contact U! Call from Landline 09064019788 BOX42WR29C, 150PPM",
       "Are you unique enough? Find out from 30th August. www.areyouunique.co.uk"
      ]
spam_prediction=p_classifier.predict(email)
spam_prediction

array([0, 0, 0, 1, 1])